In [1]:
## Image classification using RandomForest: An example in Python using CIFAR10 Dataset

def Snippet_349(): 

    print()
    print(format('Image classification using RandomForest: An example in Python using CIFAR10 Dataset','*^88'))

    import warnings
    warnings.filterwarnings("ignore")    
    
    # load libraries
    from keras.datasets import cifar10
    from sklearn import metrics
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.model_selection import cross_val_score    

    import time
    start_time = time.time()

    # data: shuffled and split between train and test sets
    (X_train, y_train), (X_test, y_test) = cifar10.load_data()

    # X_train is 50000 rows of 3x32x32 values --> reshaped in 50000 x 3072
    RESHAPED = 3072

    X_train = X_train.reshape(50000, RESHAPED)
    X_test = X_test.reshape(10000, RESHAPED)
    X_train = X_train.astype('float32')
    X_test = X_test.astype('float32')

    y_train = y_train.flatten()
    y_test = y_test.flatten()

    # normalize the datasets
    X_train /= 255.
    X_test /= 255.

    print(X_train.shape[0], 'train samples')
    print(X_test.shape[0], 'test samples')
    
    # fit a RandomForest model to the data
    model = RandomForestClassifier(n_estimators = 10)

    cv_results = cross_val_score(model, X_train, y_train, 
                   cv = 2, scoring='accuracy', n_jobs = -1, verbose = 1)    

    model.fit(X_train, y_train)
    
    print(); print(cv_results)    
    print(); print(model)

    # make predictions
    expected_y  = y_test
    predicted_y = model.predict(X_test)

    # summarize the fit of the model
    print(); print(metrics.classification_report(expected_y, predicted_y))
    print(); print(metrics.confusion_matrix(expected_y, predicted_y))

    print()
    print("Execution Time %s seconds: " % (time.time() - start_time))    

Snippet_349()


**Image classification using RandomForest: An example in Python using CIFAR10 Dataset***


2022-09-27 22:20:41.877503: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


170498071/170498071 [==============================] - 7s 0us/step
50000 train samples
10000 test samples


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 out of   2 | elapsed:   15.9s finished
[Parallel(n_jobs=-1)]: Done   2 out of   2 | elapsed:   15.8s remaining:    0.0s



[0.339   0.33756]

RandomForestClassifier(n_estimators=10)

              precision    recall  f1-score   support

           0       0.40      0.56      0.46      1000
           1       0.37      0.46      0.41      1000
           2       0.25      0.31      0.28      1000
           3       0.23      0.23      0.23      1000
           4       0.30      0.31      0.31      1000
           5       0.33      0.28      0.30      1000
           6       0.39      0.33      0.36      1000
           7       0.44      0.31      0.36      1000
           8       0.55      0.50      0.53      1000
           9       0.44      0.35      0.39      1000

    accuracy                           0.36     10000
   macro avg       0.37      0.36      0.36     10000
weighted avg       0.37      0.36      0.36     10000


[[558  60  68  37  33  24  20  25 134  41]
 [ 90 455  55  65  29  44  37  28  52 145]
 [134  71 312  96 143  73  81  45  22  23]
 [ 89  77 127 234  90 154  90  56  31  52]
 [ 67  