## METHODS COMPARISON USING CIFAR100 WITH 100 CLASSES - BINARY

On this file, the logistic regression proccess is done in order to compare it with the results of the Structure Predictions package. \
We find out that there are some considerable differences. 

For this exercice we use the CIFAR100 dataset provided by Keras. This is a dataset of 50,000 32x32 color training images and 10,000 test images, labeled over 100 fine-grained classes that are grouped into 20 coarse-grained classes. 

In [1]:
from sklearn import metrics

In [2]:
from keras.datasets import cifar100
import matplotlib.pyplot as plt
import numpy as np

import time


# Download dataset of CIFAR-100 (Canadian Institute for Advanced Research)
(X_train,Y_train),(X_test,Y_test) = cifar100.load_data()
 
# Check the shape of the array
print('x_train shape:', X_train.shape)
print('x_test shape:', X_test.shape)
print('y_train shape:', Y_train.shape)
print('y_test shape:', Y_test.shape)
 
# Number of data set samples 
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')
 
# Data format confirmation
print(type(X_test))
print(type(Y_test[0]))

2022-09-27 22:18:57.112707: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


169001437/169001437 [==============================] - 7s 0us/step
x_train shape: (50000, 32, 32, 3)
x_test shape: (10000, 32, 32, 3)
y_train shape: (50000, 1)
y_test shape: (10000, 1)
50000 train samples
10000 test samples
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### Organizing data

We just want the first 10 categories of the dataset, so that's why we create a new train dataset and test dataset with those labels as below

In [3]:
print('Number of records for 10 classes X train',X_train.shape)
print('Number of records for 10 classes X test',X_test.shape)
print('Number of records for 10 classes Y train',Y_train.shape)
print('Number of records for 10 classes Y test',Y_test.shape)

Number of records for 10 classes X train (50000, 32, 32, 3)
Number of records for 10 classes X test (10000, 32, 32, 3)
Number of records for 10 classes Y train (50000, 1)
Number of records for 10 classes Y test (10000, 1)


In [5]:
X_train.shape

(50000, 32, 32, 3)

In [6]:
#!/usr/bin/python
import numpy as np

a=np.array([6,1,5,0,2,8,5,2,7,4])
b=np.array(np.zeros((10)))

for i in range(10):
    #b[i]=bin(int(a[i])).zfill(6)
    b[i]=bin(int(a[i]))[2:].zfill(8)

In [6]:
b

array([ 110.,    1.,  101.,    0.,   10., 1000.,  101.,   10.,  111.,
        100.])

## Converting to binary all the data

#### Binary for X_train

In [7]:
X_train_flat=np.array(np.zeros((50000, 3072)))

In [8]:
for i in range(X_train.shape[0]):
    #X_train_flat[i]= X_train[i]
    X_train_flat[i]= X_train[i].flatten()

In [9]:
X_train_flat.shape

(50000, 3072)

In [10]:
len(X_train_flat[1])

3072

In [11]:
bbin_X_train1= np.array(np.zeros((3072)))
bin_X_train1=X_train_flat[1]

X_train_bin= np.array(np.zeros((50000, 3072)))

for k in range(50000):
   for i in range(3072):
      X_train_bin[k][i]=bin(int(X_train_flat[k][i]))[2:].zfill(8)

KeyboardInterrupt: 

In [12]:
print("decimal: ", X_train_flat[1] , " binary: " , X_train_bin[1])

decimal:  [255. 255. 255. ... 255. 255. 255.]  binary:  [11111111. 11111111. 11111111. ... 11111111. 11111111. 11111111.]


In [13]:
X_train_bin[1][4]

11111101.0

### Binary for X test

In [14]:
X_test_flat=np.array(np.zeros((10000, 3072)))

In [15]:
for i in range(X_test.shape[0]):
    #X_train_flat[i]= X_train[i]
    X_test_flat[i]= X_test[i].flatten()

In [16]:
X_test_flat.shape

(10000, 3072)

In [17]:
len(X_test_flat[1])

3072

In [18]:
X_test_bin= np.array(np.zeros((10000, 3072)))

for k in range(10000):
   for i in range(3072):
      X_test_bin[k][i]=bin(int(X_test_flat[k][i]))[2:].zfill(8)

In [19]:
print("decimal: ", X_test_flat[1] , " binary: " , X_test_bin[1])

decimal:  [113. 130.  98. ...  84.  92.  67.]  binary:  [ 1110001. 10000010.  1100010. ...  1010100.  1011100.  1000011.]


In [20]:
X_test_bin.shape

(10000, 3072)

### Binary for Y train

In [21]:
Y_train_bin= np.array(np.zeros((50000, 1)))

for k in range(50000):
   Y_train_bin[k]=bin(int(Y_train[k]))[2:].zfill(8)

In [22]:
print("decimal: ", Y_train[1] , " binary: " , Y_train_bin[1])

decimal:  [29]  binary:  [11101.]


In [23]:
Y_train_bin.shape

(50000, 1)

### Binary for Y test

In [24]:
Y_test_bin= np.array(np.zeros(Y_test.shape))

for k in range(Y_test.shape[0]):
   Y_test_bin[k]=bin(int(Y_test[k]))[2:].zfill(8)

In [25]:
print("decimal: ", Y_test[1] , " binary: " , Y_test_bin[1])

decimal:  [33]  binary:  [100001.]


In [26]:
Y_test_bin.shape

(10000, 1)

In [29]:
print("First 5 entries of X_train",X_train[0:5])
print("First 5 entries of X_test",X_test[0:5])
print("First 5 entries of Y_train",Y_train[0:5])
print("First 5 entries of Y_test",Y_test[0:5])

First 5 entries of X_train [[[[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [195 205 193]
   [212 224 204]
   [182 194 167]]

  [[255 255 255]
   [254 254 254]
   [254 254 254]
   ...
   [170 176 150]
   [161 168 130]
   [146 154 113]]

  [[255 255 255]
   [254 254 254]
   [255 255 255]
   ...
   [189 199 169]
   [166 178 130]
   [121 133  87]]

  ...

  [[148 185  79]
   [142 182  57]
   [140 179  60]
   ...
   [ 30  17   1]
   [ 65  62  15]
   [ 76  77  20]]

  [[122 157  66]
   [120 155  58]
   [126 160  71]
   ...
   [ 22  16   3]
   [ 97 112  56]
   [141 161  87]]

  [[ 87 122  41]
   [ 88 122  39]
   [101 134  56]
   ...
   [ 34  36  10]
   [105 133  59]
   [138 173  79]]]


 [[[255 255 255]
   [253 253 253]
   [253 253 253]
   ...
   [253 253 253]
   [253 253 253]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
 

### Structure Predictions method

We procceed to create execute the Structure predictions method in order to identify differences and get some conclusions.

In [30]:
from stpredictions.models.IOKR.model import IOKR


Here we implement the class IOKR2 due to some issues:

In [31]:
type(X_train_bin[0][0])

numpy.float64

In [34]:
#from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score

from stpredictions.models.IOKR.model import IOKR

#X, Y, _, _ = load_bibtex()

#X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

clf = IOKR()
clf.verbose = 1
L = 1e-5
clf.fit(X=X_train_bin[0:100], Y=Y_train_bin[0:100], L=L)
Y_pred_test = clf.predict(X_test=X_test_bin, Y_candidates=Y_test_bin)
f1_test = f1_score(Y_pred_test, Y_test_bin, average='weighted')
print( "Test f1 score:", f1_test)

Fitting time: 0.11579060554504395 in s
Decoding time: 17.80364155769348 in s
Test f1 score: 0.017453556218021988


In [35]:
X_train_flat.shape[1]

3072

Currently, we haven't found a good result. As it can be seen in the following table, the precision, recall and f1-score are usually 0.
This problem is similar to the problems we had without the encoded dataset but using the original one. 

In [37]:
from sklearn.metrics import classification_report
print(classification_report(Y_pred_test,Y_test_bin))

              precision    recall  f1-score   support

         0.0       0.25      0.01      0.02      2838
         1.0       0.00      0.00      0.00         0
        10.0       0.00      0.00      0.00         0
        11.0       0.00      0.00      0.00         0
       100.0       0.00      0.00      0.00         0
       101.0       0.00      0.00      0.00         0
       110.0       0.00      0.00      0.00         0
       111.0       0.00      0.00      0.00         0
      1000.0       0.00      0.00      0.00         0
      1001.0       0.00      0.00      0.00         0
      1010.0       0.00      0.00      0.00         0
      1011.0       0.00      0.00      0.00         0
      1100.0       0.00      0.00      0.00         0
      1101.0       0.00      0.00      0.00         0
      1110.0       0.00      0.00      0.00         0
      1111.0       0.00      0.00      0.00         0
     10000.0       0.00      0.00      0.00         0
     10001.0       0.00    

/home/daniel/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/daniel/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/daniel/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [44]:
Y_pred_test

array([[      0.],
       [      0.],
       [      0.],
       ...,
       [      0.],
       [      0.],
       [1100011.]])

In [39]:
# Implementation
import time
# from sklearn.model_selection import KFold
from sklearn.metrics.pairwise import linear_kernel, polynomial_kernel, rbf_kernel
# from sklearn.metrics import f1_score
import numpy as np
# import pandas as pd
# from stpredictions.datasets.load_data import load_bibtex
# from sklearn.model_selection import train_test_split
# import arff
from numpy.linalg import inv
# import os

# from line_profiler import LineProfiler

"""
Created on December 12, 2021
"""


class IOKR2:
    """
    Class used to apply Input and Output Kernel Regression
    """

    
    def __init__(self):
        """
        Initialization of the below parameters.
        Parameters
        ----------
        X_train :  sparse matrix - containing explanatory variables of the train set
        Y_train: sparse matrix - containing target variable of the train set
        Ky: output scalar kernel
        M: gram matrix on training set
        verbose: binary - display more parameters
        linear:
        """
        self.X_train = None
        self.Y_train = None
        self.Ky = None
        self.M = None
        self.verbose = 0
        self.input_kernel = None
        self.output_kernel = None

  
    def fit(self, X, Y, L, input_kernel='linear', input_kernel_param=None):
        """
        Model Fitting
        """

        # save input and output training data
        self.X_train, self.Y_train = X, Y

        # instantiate input kernel parameter when not given
        if input_kernel_param is None:
            if input_kernel == 'rbf':
                input_kernel_param = 1.
            elif input_kernel == 'polynomial':
                input_kernel_param = [3, None, 1]

        # define input kernel
        if input_kernel == 'linear':
            self.input_kernel = lambda A, B: linear_kernel(A, B)
        elif input_kernel == 'polynomial':
            self.input_kernel = lambda A, B: polynomial_kernel(A, B, degree=input_kernel_param[0],
                                                               gamma=input_kernel_param[1], coef0=input_kernel_param[2])
        elif input_kernel == 'rbf':
            self.input_kernel = lambda A, B: rbf_kernel(A, B, gamma=input_kernel_param)
        else:
            self.input_kernel = input_kernel

        # compute input gram matrix
        Kx = self.input_kernel(X, X)

        # kernel ridge regression training computation: n x n matrix inversion
        t0 = time.time()
        n = Kx.shape[0]
        self.M = np.linalg.inv(Kx + n * L * np.eye(n))
        if self.verbose > 0:
            print(f'Fitting time: {time.time() - t0} in s')

    def alpha(self, X_test):

        Kx = self.input_kernel(self.X_train, X_test)
        A = self.M.dot(Kx)

        return A


    def predict(self, X_test, Y_candidates, output_kernel='linear', output_kernel_param=None):

        """
        Model Prediction
        """

        # instantiate output kernel parameter when not given
        if output_kernel_param is None:
            if output_kernel == 'rbf':
                output_kernel_param = 1.
            elif output_kernel == 'polynomial':
                output_kernel_param = [3, None, 1]

        # define output kernel
        if output_kernel == 'linear':
            self.output_kernel = lambda A, B: linear_kernel(A, B)
        elif output_kernel == 'polynomial':
            self.output_kernel = lambda A, B: polynomial_kernel(A, B, degree=output_kernel_param[0],
                                                                gamma=output_kernel_param[1],
                                                                coef0=output_kernel_param[2])
        elif output_kernel == 'rbf':
            self.output_kernel = lambda A, B: rbf_kernel(A, B, gamma=output_kernel_param)
        else:
            self.output_kernel = output_kernel

        # compute output gram matrix
        Ky = self.output_kernel(self.Y_train, Y_candidates)

        # compute prediction
        t0 = time.time()
        Alpha = self.alpha(X_test)
        scores = Ky.transpose().dot(Alpha)
        idx_pred = np.argmax(scores, axis=0)
        Y_pred = Y_candidates[idx_pred]
        if self.verbose > 0:
            print(f'Decoding time: {time.time() - t0} in s')

        return Ky,Alpha,scores,idx_pred,Y_pred




If we change the Y_candidates paramter for the Identity matrix, we get the following problem:

In [41]:
clf = IOKR2()
clf.verbose = 1
L =1e-6
#Just using a quantity of 100 due to a shape problem 
clf.fit(X=X_train_bin[0:100], Y=Y_train_bin[0:100], L=L, input_kernel='linear')
Ky,Alpha,scores,idx_pred,Y_pred_test = clf.predict(X_test=X_test_bin, Y_candidates=np.eye(100))
#f1_test_st = f1_score(Y_pred_test, Y_test, average='weighted')
#print( "Test f1 score:", f1_test_st)
print(Y_pred_test[1])

Fitting time: 0.30271005630493164 in s


ValueError: Incompatible dimension for X and Y matrices: X.shape[1] == 1 while Y.shape[1] == 100