In [1]:
## Image classification using RandomForest: An example in Python using CIFAR10 Dataset

def Snippet_349(): 

    print()
    print(format('Image classification using RandomForest: An example in Python using CIFAR10 Dataset','*^88'))

    import warnings
    warnings.filterwarnings("ignore")    
    
    # load libraries
    from keras.datasets import cifar10
    from sklearn import metrics
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.model_selection import cross_val_score    

    import time
    start_time = time.time()

    # data: shuffled and split between train and test sets
    (X_train, y_train), (X_test, y_test) = cifar10.load_data()

    # X_train is 50000 rows of 3x32x32 values --> reshaped in 50000 x 3072
    RESHAPED = 3072

    X_train = X_train.reshape(50000, RESHAPED)
    X_test = X_test.reshape(10000, RESHAPED)
    X_train = X_train.astype('float32')
    X_test = X_test.astype('float32')

    y_train = y_train.flatten()
    y_test = y_test.flatten()

    # normalize the datasets
    X_train /= 255.
    X_test /= 255.

    print(X_train.shape[0], 'train samples')
    print(X_test.shape[0], 'test samples')
    
    # fit a RandomForest model to the data
    model = RandomForestClassifier(n_estimators = 10)

    cv_results = cross_val_score(model, X_train, y_train, 
                   cv = 2, scoring='accuracy', n_jobs = -1, verbose = 1)    

    model.fit(X_train, y_train)
    
    print(); print(cv_results)    
    print(); print(model)

    # make predictions
    expected_y  = y_test
    predicted_y = model.predict(X_test)

    # summarize the fit of the model
    print(); print(metrics.classification_report(expected_y, predicted_y))
    print(); print(metrics.confusion_matrix(expected_y, predicted_y))

    print()
    print("Execution Time %s seconds: " % (time.time() - start_time))    

Snippet_349()


**Image classification using RandomForest: An example in Python using CIFAR10 Dataset***


2022-08-11 11:39:03.420941: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-08-11 11:39:06.317831: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-08-11 11:39:06.317865: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


170498071/170498071 [==============================] - 13s 0us/step
50000 train samples
10000 test samples


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 out of   2 | elapsed:   30.4s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   2 out of   2 | elapsed:   30.4s finished



[0.33668 0.33568]

RandomForestClassifier(n_estimators=10)

              precision    recall  f1-score   support

           0       0.38      0.53      0.44      1000
           1       0.36      0.44      0.39      1000
           2       0.25      0.32      0.28      1000
           3       0.23      0.22      0.22      1000
           4       0.30      0.30      0.30      1000
           5       0.30      0.26      0.28      1000
           6       0.40      0.33      0.36      1000
           7       0.43      0.30      0.35      1000
           8       0.54      0.48      0.51      1000
           9       0.42      0.34      0.38      1000

    accuracy                           0.35     10000
   macro avg       0.36      0.35      0.35     10000
weighted avg       0.36      0.35      0.35     10000


[[529  67  84  34  25  14  20  33 142  52]
 [ 95 436  46  60  34  44  41  34  70 140]
 [125  58 319  96 152  67  96  47  17  23]
 [ 97  83 122 223 103 159  79  65  24  45]
 [ 88  